src/stackwalk.c
Add option to `jl_print_task_backtraces(bool)` to control whether or not to print DONE tasks (https://github.com/JuliaLang/julia/pull/47933).
To be merged once the backport is merged in RelationalAI's code
=> Add 47933.patch

src/stackwalk.c
Backports http://github.com/JuliaLang/julia/pull/45564 to RAI julia.
=> Backport PR 45564

base/initdefs.jl, test/atexit.jl
Backports https://github.com/julialang/julia/pull/49868
=> Backport 49868

src/gc-pages.c, src/gc-stacks.c, src/gc.c
Disable huge page to avoid THP collapsing ranges of smaller 4 KiB pages into huge pages that can waste lots of memory e.g., when we create lots of tasks.
cf.[ raicode PR](https://github.com/RelationalAI/raicode/pull/14546)
=> Disable huge pages for every mmap call

base/channels.jl, src/stackwalk.c
And complete the PR 50858 backport.
The prepending of thread ID on stack traces is useful in our environment but likely too noisy for standard Julia so we don't intend to add this upstream.
=> Prepend threadid to stacktraces

src/julia_internal.h, src/signals-win.c, src/stackwalk.c
Correctly prepend `[signal (X)] thread Y ` to each backtrace line that is displayed.
=> RAI: redo prepending to backtrace output

doc/src/manual/profile.md, src/gc-alloc-profiler.h, src/gc.c, src/jl_exported_funcs.inc, src/llvm-final-gc-lowering.cpp, src/llvm-late-gc-lowering.cpp, src/llvm-pass-helpers.cpp, stdlib/Profile/test/allocs.jl, test/llvmpasses/alloc-opt-gcframe.jl, test/llvmpasses/final-lower-gc.ll, test/llvmpasses/late-lower-gc-addrspaces.ll, test/llvmpasses/late-lower-gc.ll, test/llvmpasses/pipeline-o0.jl
Backports PR https://github.com/JuliaLang/julia/pull/50337 for RAI julia v1.9.2
=> Backport #50337: Allocation Profiler: Types for all allocations

src/gc-pages.c
Disable MADV_FREE. Use MADV_DONTNEED.
See https://github.com/RelationalAI/raicode/pull/15092
=> Bck v1.9.2+rai+madv free

.github/workflows/nightly-rebase-upstream.yml
I'm opening this PR against the `master+RAI` branch, which I think we should switch as the "default" branch of this repo.
=> Add nightly rebase of branches with upstream julia

src/gc.c
resetting pool_live_bytes after each GC accidentally got removed when merging the parallel marking [PR](https://github.com/RelationalAI/julia/commit/6085d74ea73b2cace6fe1a608a19fc6bc6f1a1a1#diff-76b4d6ef0f7d9c2a6855e1ef7b0f7c94ddc68fcca2cdcd69e6d2b9007c279fde)
=> Fix pool live bytes merge

src/gc-stacks.c, src/gc.h, test/threads.jl
Backport https://github.com/JuliaLang/julia/pull/51301: export num_stack_mappings
Export num_stack_mappings to track the number of in-flight stack mappings and tasks in application #51301
=> Backport https://github.com/JuliaLang/julia/pull/51301: export num_stack_mappings

.github/CODEOWNERS, .github/pull_request_template.md, .github/workflows/LabelCheck.yml, .github/workflows/labeler.yml, .github/workflows/stale.yml
We want to set the default branch on this repo to be the version that we're currently using, which is `v1.9.2+RAI`, but the PR template and the workflows that run on a schedule must be in the default branch... so this PR adds those GitHub things to `v1.9.2+RAI`.
this PR
- copies the files from `master+RAI` (current default)
- removes the `codeowerns` file that doesn't apply to this fork (we could always add our own one back later)
- adds a workflow for closing stale PRs [this change can move to it's own PR if you prefer?]
in future, when we change default branch, it should be a simple as copying across the `.github/` directory, e.g.
```
git checkout new-default-branch                # switch to new branch
git checkout old-default-branch -- .github/    # copy across the files from the old …
```
=> Add GitHub template and workflows needed on the default branch

src/gc-debug.c, src/gc-pages.c, src/gc.c, src/gc.h, src/julia_threads.h, src/partr.c
X-ref: https://github.com/JuliaLang/julia/pull/51282.
=> Backport parallel sweeping of object pools

.github/labeler.yml
Got missed in https://github.com/RelationalAI/julia/pull/70 -- needed for the auto-labelling to work (as without is we get failures like https://github.com/RelationalAI/julia/actions/runs/6300339730)
=> Fix labeler workflow

.github/workflows/update-upstream-branches.yml
- close RAI-16458
- makes it easier to see RAI-specific changes (e.g. comparisons PRs like https://github.com/RelationalAI/julia/pull/46 would have clearer/smaller diffs)
- PR is to the default branch, since scheduled workflows need to be on default branch
- (but no way to test a new GitHub workflow before it's merged 😞)
=> [RAI-16458] Add workflow to keep up-to-date with upstream branches

src/stackwalk.c
Backport https://github.com/JuliaLang/julia/pull/51413.
=> Backport don't print task backtrace for GC threads

.github/workflows/update-upstream-branches.yml
You can see this workflow now ran successfully with these fixes: https://github.com/RelationalAI/julia/actions/runs/6325571167
Follow-up to https://github.com/RelationalAI/julia/pull/76. Sorry for the follow-up PR; we can only test a GitHub Actions workflow once it's already on the default branch.
=> Fix workflow that pulls upstream branches

src/Makefile, src/gc-stacks.c, src/gc.c, src/interpreter.c, src/julia.h, src/julia_internal.h, src/julia_threads.h, src/mtarraylist.c, src/signals-mach.c, src/signals-unix.c, src/signals-win.c, src/stackwalk.c, src/threading.c
Backport https://github.com/JuliaLang/julia/pull/51430.
=> Backport support for async backtraces

src/gc.c
Shouldn't affect correctness and should have a minimal effect on performance. We already fixed this upstream in https://github.com/JuliaLang/julia/pull/49780.
=> remove spurious gc_try_claim_and_push

src/gc-debug.c, src/gc-pages.c, src/gc.c, src/gc.h, src/julia_internal.h
Backports https://github.com/JuliaLang/julia/pull/49644 for further performance assessment.
=> Backport promote objects more eagerly (#49644)

src/stackwalk.c
Currently the output is 0-based, so we see:
```
...
thread (0) ijl_apply_generic at /nix/store/6lxp69px3vnal0csypfvm3lv2dwlllwv-julia-1.9.2/lib/julia/libjulia-internal.1.9.dylib (unknown line)
thread (0) do_call at /nix/store/6lxp69px3vnal0csypfvm3lv2dwlllwv-julia-1.9.2/lib/julia/libjulia-internal.1.9.dylib (unknown line)
...
```
In Julia, thread ID is 1-based, so this output is wrong. This PR fixes that.
This has a messy history. The following commits should be merged with this one when we next upgrade:
- `0457f8995eb49158adcab9b12d21d9d31e9e05d4`
- `e015382634953445155c9fa4f51aba05235e8313`
- `8f409da5c564d8fd9e9a2d0fe19235a710fedd09`
=> Change backtrace prefix of thread ID to 1-based

base/reflection.jl, src/cgutils.cpp, src/codegen.cpp, src/codegen_shared.h, src/julia.h, src/llvm-final-gc-lowering.cpp, src/llvm-pass-helpers.cpp, src/llvm-pass-helpers.h, src/llvm-ptls.cpp, test/compiler/codegen.jl
Backport https://github.com/JuliaLang/julia/pull/41616 and https://github.com/JuliaLang/julia/pull/47393 as an attempt to fix https://relationalai.atlassian.net/browse/RAI-13268.
=> Backport safepoints at function entry

src/gc-pages.c
See title. CC complains about this.
=> add void signature to functions which take no arguments

src/stackwalk.c
More backtrace prepending, this time to the text output by `jl_print_task_backtraces()`.
This should be squashed with the following commits when we upgrade:
- `0457f8995eb49158adcab9b12d21d9d31e9e05d4`
- `e015382634953445155c9fa4f51aba05235e8313`
- `8f409da5c564d8fd9e9a2d0fe19235a710fedd09`
=> Prepend "thread (%d)" to output from `jl_print_task_backtraces()`

src/mach_dyld_atfork.tbd, src/signals-mach.c
Backport fixes for a deadlock in MacOS.
=> Backport MacOS dyld fixes

src/gc-pages.c
Our page pool stats commit didn't cherry-pick cleanly. Port them to 1.10 in this PR.
=> port pool stats to 1.10

contrib/generate_precompile.jl, src/init.c, src/options.h, src/threading.c
Telemetry for Julia's threads.
This capability is build-time enabled by setting `JL_HEARTBEAT_THREAD` in `src/options.h`, which causes Julia to start a heartbeat thread that quickly goes to sleep.
Control heartbeats with `jl_heartbeat_enable(heartbeat_s, n_reports, reset_reporting_after_s)`. Heartbeats are disabled if `heartbeat_s <= 0`. Otherwise, you must call `jl_heartbeat()` at least one time every `heartbeat_s`. If this does not happen, the heartbeat thread will call `jl_print_task_backtraces(0)`. If `jl_heartbeat()` continues to not be called, we double the reporting interval up to a maximum of 60 times the `heartbeat_s` and report up to `n_reports` times altogether. Once `jl_heartbeat()` is called again, the number of reports is reset immediately but we only reset the reporting …
=> Add heartbeat capability

src/gc.c, src/julia_threads.h
`pool_live_bytes` was previously lazily updated during the GC, meaning it was only accurate right after a GC.
Make this metric accurate if gathered after a GC has happened.
=> eagerly update pool live bytes metric

src/gc.c
This was fixed upstream a while back. We didn't backport the fix for some reason.
=> missing gc_mark_push_remset in obj32

src/gc.c
Otherwise we may just observe `gc_n_threads = 0` (`jl_gc_collect` sets it to 0 in the very end of its body) and this function becomes a no-op.
=> bugfix: load jl_n_threads in jl_gc_pool_live_bytes (#52034)

src/gc.c
One more bugfix related to the `pool_live_bytes` metric.
Ran one of the large scale customer benchmarks and sanity-checked the metric on that. Also sanity-checked on a micro GCBenchmark. Hopefully will be the last bugfix coming from that PR.
=> bugfix: don't set pool_live_bytes to zero at the end of GC

test/channels.jl, test/stack_overflow.jl
Backports PR https://github.com/JuliaLang/julia/pull/49702.
Original description:
Per @vtjnash's comment here:
https://github.com/JuliaLang/julia/pull/49508/files/bca5ac79d04fb2a95f3b9a7b7448fe5b478f950b#r1186161259
> the handling of this error is quite bad and sometimes ends up breaking
> the process (as I found out today trying to debug something completely
> unrelated)
This is a Tests-only PR
=> Backport: Move test of stackoverflow with close(::Channel) to stack_overflow.jl (#49702)

src/gc.c, src/gc.h
Backports https://github.com/JuliaLang/julia/pull/52164.
=> add some instrumentation to measure page utilization per size class

base/timing.jl, src/gc.c, src/gc.h
Backports https://github.com/JuliaLang/julia/pull/52390.
=> functionality to expose page utilization at the Julia level

src/coverage.cpp, src/julia_internal.h
Backports https://github.com/JuliaLang/julia/pull/52456
Fixes https://relationalai.atlassian.net/browse/RAI-19583
=> Make `jl_write_coverage_data` dllexported again

src/gc.c, src/julia_gcext.h
Backports the memory pressure callback to 1.9.
=> backport memory pressure callback to 1.9

src/gc.c, src/gc.h
Backports https://github.com/JuliaLang/julia/pull/52294.
=> [RAI-19749] GC scheduler refinements (#52294)

src/gc.c, src/jl_exported_funcs.inc, src/jloptions.c, src/julia.h, src/julia_internal.h
DLL export `jl_gc_set_max_memory`. Functionality has been requested by the runtime team.
=> export `jl_gc_set_max_memory` (#47545)

src/gc-heap-snapshot.cpp, src/gc-heap-snapshot.h, src/gc.c, src/gc.h
_What does this PR do?_
This PR is to fix the issue: https://github.com/JuliaLang/julia/issues/52432
1. Fixed unrooted nodes from gc_mark_roots and added a GC root to them
2. Fixed unrooted nodes from gc_mark_finlist and added a finlist root to them
3. Added logic to check nodes without any incoming edges and print them out when serialize heap snapshot
The resulting output is as follows for snapshotting julia process
```
julia> using Profile
julia> Profile.take_heap_snapshot("jf-julia.heapsnapshot")
node count: 1384919
edge count: 4407344
orphan node count: 0
orphan nodes: []
"jf-julia.heapsnapshot"
```
The containment view on chrome DevTools:
=> add gc roots and gc finalist roots to fix unrooted nodes

src/gc-debug.c, src/gc.c, src/gc.h, test/testenv.jl
We'll likely be running with 1.9 GC heuristics on top of 1.10.
=> revert GC heuristics back to 1.9

src/gc-heap-snapshot.cpp, src/gc-heap-snapshot.h, stdlib/Profile/docs/src/index.md, stdlib/Profile/src/Profile.jl, stdlib/Profile/src/heapsnapshot_reassemble.jl, stdlib/Profile/test/heapsnapshot_reassemble.jl, stdlib/Profile/test/runtests.jl
* Streaming the heap snapshot!
This should prevent the engine from OOMing while recording the snapshot!
Now we just need to sample the files, either online, before downloading, or offline after downloading :)
If we're gonna do it offline, we'll want to gzip the files before downloading them.
* Allow custom filename; use original API
* Support legacy heap snapshot interface. Add reassembly function.
* Add tests
* Apply suggestions from code review
* Update src/gc-heap-snapshot.cpp
* Change to always save the parts in the same directory
This way you can always recover from an OOM
* Fix bug in reassembler: from_node and to_node were in the wrong order
* Fix correctness mistake: The edges have to be reordered according to the node order. That's the whole reason this is tricky.
But i'm not …
=> Change to streaming out the heap snapshot data

src/gc-heap-snapshot.cpp, src/gc-heap-snapshot.h, stdlib/Profile/docs/src/index.md, stdlib/Profile/src/Profile.jl, stdlib/Profile/src/heapsnapshot_reassemble.jl, stdlib/Profile/test/heapsnapshot_reassemble.jl, stdlib/Profile/test/runtests.jl
This PR is to continue the work on the following PR:
Prevent OOMs during heap snapshot: Change to streaming out the snapshot data (#51518 )
Here are the commit history:
```
* Streaming the heap snapshot!
This should prevent the engine from OOMing while recording the snapshot!
Now we just need to sample the files, either online, before downloading, or offline after downloading :)
If we're gonna do it offline, we'll want to gzip the files before downloading them.
* Allow custom filename; use original API
* Support legacy heap snapshot interface. Add reassembly function.
* Add tests
* Apply suggestions from code review
* Update src/gc-heap-snapshot.cpp
* Change to always save the parts in the same directory
This way you can always recover from an OOM
* Fix bug in reassembler: from_node and …
```
=> Change to streaming out the heap snapshot data (#52854)

src/gc.c
Cherry-pick the parts of https://github.com/JuliaLang/julia/pull/53355 which are relevant to the 1.10 GC.
=> gc scheduler synchronization fixes to 1.10 (#53661)

.github/labeler.yml, .github/pull_request_template.md, .github/workflows/labeler.yml, .github/workflows/stale.yml, .github/workflows/update-upstream-branches.yml
Copied from the `v1.9.2+RAI` branch via `git checkout v1.9.2+RAI -- .github`
=>  Add GitHub template and workflows needed on the default branch

base/checked.jl, base/intfuncs.jl, doc/src/base/math.md, test/checked.jl, test/compiler/ssair.jl
Backports https://github.com/JuliaLang/julia/pull/52849.
Only conflicts were in the `compiler/ssair` tests, which now pass:
```Julia
julia> Base.runtests(["compiler/ssair"])
Running parallel tests with:
nworkers() = 1
nthreads() = 1
Sys.CPU_THREADS = 4
Sys.total_memory() = 64.000 GiB
Sys.free_memory() = 21.334 GiB
Test       (Worker) | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)
compiler/ssair  (1) |        started at 2024-03-19T00:05:07.301
compiler/ssair  (1) |     3.35 |   0.03 |  0.9 |     320.90 |   346.09
Test Summary: | Pass  Total  Time
Overall     |  140    140  4.0s
SUCCESS
```
=> Backport checked pow

src/codegen-stubs.c, src/gf.c, src/jitlayers.cpp, src/julia_internal.h
When multiple threads concurrently attempt to compile the same method, `--trace-compile` could emit duplicate `precompile` statements. This small tweak eliminates one source of these duplicates.
=> Remove some duplicates from emitted compilation traces

src/gc.c
Backports https://github.com/JuliaLang/julia/pull/53661 to v1.9.2+RAI.
=> gc scheduler synchronization fixes to 1.9 (#53661)

base/options.jl, src/init.c, src/jl_uv.c, src/jloptions.c, src/jloptions.h, src/julia_internal.h, src/signal-handling.c, src/signals-unix.c, src/signals-win.c
Creates a `--safe-crash-log-file` that is used to redirect crash logs created while we were running the signal handler.
For now it's only x86_64 Linux but shouldn't be that hard to port it to MacOS.
Example usage:
```
./julia --safe-crash-log-file=/tmp/foobar.txt -e "p = Ptr{Any}(C_NULL); b = unsafe_load(p, 0)"
```
Which leads to:
```
cat /tmp/foobar.txt 
[83691] signal (11.1): Segmentation fault
in expression starting at none:1
signal (11) thread (1) unsafe_load at ./pointer.jl:119
signal (11) thread (1) unknown function (ip: 0x7f477566a17f)
signal (11) thread (1) _jl_invoke at /home/ubuntu/julia-RAI/src/gf.c:2895 [inlined]
signal (11) thread (1) ijl_apply_generic at /home/ubuntu/julia-RAI/src/gf.c:3077
signal (11) thread (1) jl_apply at /home/ubuntu/julia-RAI/src/julia.h:1982 [inlined] …
```
=> --safe-crash-log-file flag

src/jl_uv.c, src/partr.c, src/task.c
A common idiom used throughout the codebase is to get a pointer to thread-local-state through `jl_current_task->ptls`.
Create a phantom task for GC threads so that we can make use of this idiom when running in the GC threads as well.
Idea originally suggested by @vchuravy, bugs are mine.
=> create phantom task for GC threads (#53815) & fix ordering in jl_safe_printf

src/gc.c
=> Correct GC bug (usage of `not_freed_enough`)

.github/labeler.yml, .github/workflows/update-upstream-branches.yml
Simplifies our automations now we're not using v1.9
=> Stop updating upstream 1.9 branch

src/signals-unix.c, src/stackwalk.c
`Ctrl+T` sends a `SIGINFO` (on Mac, `SIGUSR1` on Linux) to Julia which triggers a backtrace. RAI Julia prepends `[signal (X)] thread (Y)` to backtraces. But in signal handler context, there is no "current task" from which to get the thread ID.
This PR fixes the problem by checking to see if we're in signal handler context before calling `jl_threadid()`.
=> RAI: do not prepend thread ID to backtraces from signal handler context

src/gc-pages.c, test/gc.jl
Exposes a function to get GC page size. Requested [here](https://relationalai.slack.com/archives/C068ANEBS04/p1713365676930839?thread_ts=1713365265.705269&cid=C068ANEBS04).
Example usage:
```Julia
julia> @ccall jl_get_pg_size()::UInt64
0x0000000000004000
```
=> function to query page size

src/jitlayers.cpp
As part of https://relationalai.atlassian.net/browse/RAI-24337.
This change is also going to be merged upstream as part of another PR. See https://github.com/JuliaLang/julia/pull/54140/commits/346972a527147f1f8afdee0cb9518c79cbfe0757.
=> RAI: Change optimization aggressiveness for `-O1` from `None` to `Less`

src/gc.c
Backports https://github.com/JuliaLang/julia/pull/54251.
=> fix typo in gc_mark_memory8 when chunking a large array (#54251)

stdlib/Test/src/logging.jl
Backports https://github.com/JuliaLang/julia/pull/54497 to RAI julia.
=> Backport: Make TestLogger thread-safe (introduce a lock) (#54497)

src/jl_uv.c, src/threading.c
Re-land https://github.com/RelationalAI/julia/pull/153.
=> Write heartbeat thread output to safe crash log

src/threading.c
The first GC thread's TID was set to the first thread after the default threadpool. When there are interactive threads, this is set incorrectly.
=> Fix `gc_first_tid`

src/module.c
Backports https://github.com/JuliaLang/julia/pull/54671.
> The race here is that svec might be replaced and a new binding introduced into the keyset while we hold a reference to the old svec, which led to a OOB access on the svec with the index a binding introduced at the same time. This now introduces a bounds check which will force taking the lock if we fail the lookup i.e we had a data race.
=> Backport fix for module bindings crash

src/gf.c
[This segfault](https://relationalai.slack.com/archives/CCXL42PRV/p1718659586975329). Fix is similar to https://github.com/RelationalAI/julia/pull/158.
Upstream fix is https://github.com/JuliaLang/julia/pull/54840.
=> Backport fix for another segfault

src/gc.c
I'm able to build Julia locally with this patch.
Motivation is to fix a race we may have in `gc_big_object_link/unlink` if two different threads mutate a bigval list at the same time.
=> make realloc_string explicitely allocate a new string instead of realloc'ing

src/Makefile, src/gc-page-profiler.c, src/gc-page-profiler.h, src/gc.c, src/gc.h, src/julia_internal.h, src/julia_threads.h
Brings minor performance improvements, an enhancement to the page profiler and a NFC (doc-string fix) that we merged upstream.
Good to bring these to make sure we don't fall too behind the upstream GC.
=> Bring a few minor GC patches from upstream

base/timing.jl, src/gc-debug.c, src/gc.c, src/gc.h, src/julia_threads.h, src/options.h, src/partr.c
Mostly NFCs that we merged upstream and also a minor performance improvement in `gc_sweep_pool`.
=> Bring a few more gc patches

src/gc.c, src/jl_exported_funcs.inc, src/julia.h, src/julia_threads.h, src/runtime_intrinsics.c
Let's ensure our fork doesn't fall too behind the upstream GC.
=> Bring a few more GC patches from upstream

src/Makefile, src/array.c, src/gc-debug.c, src/gc-stacks.c, src/gc-tls.h, src/gc.c, src/gc.h, src/init.c, src/jl_exported_funcs.inc, src/julia_internal.h, src/julia_threads.h, src/llvm-pass-helpers.cpp, src/partr.c, src/stackwalk.c, src/threading.c, src/threading.h, test/llvmpasses/alloc-opt-gcframe.ll, test/llvmpasses/final-lower-gc.ll, test/llvmpasses/julia-licm-fail.ll, test/llvmpasses/julia-licm-missed.ll, test/llvmpasses/julia-licm.ll
Should be NFCs or code simplifications.
https://github.com/JuliaLang/julia/pull/54936 is the only one which does more significant changes, but we already assessed its performance in the open-source benchmarks and internally as well.
=> Bring a few upstream GC patches into our fork

src/gc.c
Caps live_bytes to 0 when computing GC intervals.
=> cap live_bytes to zero in a few places where GC intervals are computed

src/array.c, src/gc.c, src/julia_internal.h
Test whether this fixes the negative GC live bytes issue.
=> dont reset maxsize in jl_array_to_string

src/array.c, src/init.c, src/julia.h
Simple dynamic race detector for `jl_array_to_string`. Here is a quick example:
```Julia
julia-RAI % ./julia -t8
_
_       _ _(_)_     |  Documentation: https://docs.julialang.org
(_)     | (_) (_)    |
_ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
| | | | | | |/ _` |  |
| | |_| | | | (_| |  |  Version 1.10.2+RAI (2024-08-14)
_/ |\__'_|_|_|\__'_|  |  v1.10.2+RAI/ec21f11718 (fork: 397 commits, 414 days)
|__/                   |
julia> a = UInt8['b' for _ in 1:1_000]
1000-element Vector{UInt8}:
0x62
0x62
0x62
0x62
0x62
0x62
0x62
0x62
0x62
0x62
0x62
⋮
0x62
0x62
0x62
0x62
0x62
0x62
0x62
0x62
0x62
0x62
julia> Threads.@threads for _ in 1:1000
String(a)
end
ERROR: racy conversion of array to string... Setting in-flight bit
ERROR: racy conversion of array to string... Resetting …
```
=> simple dynamic race detector for jl_array_to_string

src/gc-heap-snapshot.cpp, src/gc-heap-snapshot.h, stdlib/Profile/src/Profile.jl, stdlib/Profile/test/runtests.jl
Do not emit the contents of strings in heap snapshots.
=> Backport: Redact object data in heap snapshots, with option to opt-out

base/timing.jl, src/gc.c, src/gc.h
Adds individual metrics for the time spent in each phase of sweeping.
=> instrument GC to breakdown times spent in each step of sweeping

test/cmdlineargs.jl, test/gc.jl
We set the number of GC threads in our fork to the number of mutators (not half of it, as it's done upstream).
=> fix cmdlineargs test in our fork

stdlib/Dates/test/types.jl
One more PR to make JuliaLang CI in our fork a bit more stable.
=> [Dates] Make test more robust against non-UTC timezones (#55829)

src/gc.c, src/stackwalk.c, src/threading.c
Introduce a heartbeat pause/resume capability. Use this capability:
- during GC (so that long GC pauses do not cause heartbeat losses), and
- when a thread that is not the heartbeat thread prints task backtraces.
=> Adjust heartbeat behavior

base/timing.jl, src/gc.c, src/gc.h, src/threading.c, test/gc.jl
Backports https://github.com/JuliaLang/julia/pull/55826.
=> expose metric to report reasons why full GCs were triggered (#55826)

src/stackwalk.c
There was a missing re-assignment of old = -1; at the end of that loop which means in the ABA case, we accidentally actually acquire the lock on the thread despite not actually having stopped the thread; or in the counter-case, we try to run through this logic with old==-1 on the next iteration, and that isn't valid either (jl_thread_suspend_and_get_state should return failure and the loop will abort too early).
=> Backport: stackwalk: fix jl_thread_suspend_and_get_state race (#56047)

base/options.jl, doc/man/julia.1, doc/src/manual/command-line-interface.md, src/gf.c, src/jloptions.c, src/jloptions.h, test/cmdlineargs.jl
```
% ./julia --trace-compile=stderr --trace-compile-timing --start=no -e "using ProfileView"
#=   0.0 ms =# precompile(Tuple{typeof(Requires.__init__)})
#=  19.4 ms =# precompile(Tuple{typeof(Requires.isprecompiling)})
#=   0.0 ms =# precompile(Tuple{typeof(Requires.listenpkg), Any, Base.PkgId})
#=   0.0 ms =# precompile(Tuple{typeof(Requires.loaded), Base.PkgId})
#=  13.4 ms =# precompile(Tuple{typeof(Base.haskey), Base.Dict{Base.PkgId, Module}, Base.PkgId})
#=   0.0 ms =# precompile(Tuple{typeof(Requires.callbacks), Base.PkgId})
#=   0.0 ms =# precompile(Tuple{typeof(Libiconv_jll.__init__)})
#=   0.0 ms =# precompile(Tuple{typeof(Libiconv_jll.find_artifact_dir)})
#=  32.0 ms =# precompile(Tuple{typeof(Artifacts._artifact_str), Module, String, Base.SubString{String}, String, …
```
=> Backport: add `--trace-compile-timing` arg to add compile timing comments (#54662)

src/jloptions.c
Correctly recognize `--trace-compile-timing`.
=> Fix a backport error in PR 187

src/staticdata.c, src/staticdata_utils.c
Instead of always updating it. This should speed up loading only method specializations.
=> Only update the world age when a new method is loaded

cli/trampolines/trampolines_aarch64.S
This avoids a: `error: non-private labels cannot appear between .cfi_startproc / .cfi_endproc pairs` error.
That error was introduced in https://reviews.llvm.org/D155245#4657075 see also https://github.com/llvm/llvm-project/issues/72802
(cherry picked from commit a4e793ee31612625d9c48ebd89a53c3a5c0f6eb6) (cherry picked from commit 3f35094d298b41d57f3f3a8c5a9abd52bcf47b30)
_What does this PR do?_
=> Fix trampoline assembly for build on clang 18 on apple silicon (#54634)

doc/src/manual/functions.md, src/ast.c, src/datatype.c, src/flisp/flisp.h, src/gf.c, src/julia-syntax.scm, src/julia_internal.h, test/show.jl
Backports https://github.com/JuliaLang/julia/pull/53719.
=> Backport: nested function name canonicalization

src/julia_internal.h, src/signals-mach.c, src/signals-unix.c, src/threading.c
Intentionally skips the heartbeat thread from the CPU profiler, so that we don't include a large number of useless samples from `semaphore_wait_trap`.
X-ref: https://relationalai.atlassian.net/browse/RAI-31811.
=> skip heartbeat thread from CPU profile

base/lock.jl, test/threads.jl
Backport fix to wake a single task on unlocks.
=> ReentrantLock: wakeup a single task on unlock and add a short spin (#56814)

base/logging.jl, test/corelogging.jl
Backport fix to prevent failed transactions from logging bugs.
Fixes [RAI-33715](https://relationalai.atlassian.net/browse/RAI-33715).
[RAI-33715]: https://relationalai.atlassian.net/browse/RAI-33715?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add try/catch around handle_message() to catch errors during logging (#57004)

base/experimental.jl, test/channels.jl
Adds a method that allows waiting on a `Condition` with a timeout.
=> Add `Experimental.wait_with_timeout` (#57148)

base/options.jl, src/gc.c, src/jloptions.c, src/jloptions.h, src/julia_internal.h, src/stackwalk.c, test/cmdlineargs.jl, test/threads_exec.jl
Backports https://github.com/JuliaLang/julia/pull/57045.
I needed to make some minor adjustments in `jl_gc_wait_for_the_world`, because we're spinning waiting for the safepoint in 1.10, but we sleep on a condition in 1.12.
Marking as draft until I make the adjustments (e.g. pretty-printing the backtraces to JSON) to make sure this shows up on DD.
=> add option to dump backtrace of stop-the-world straggler (#57045)

base/loading.jl
If we set `Base.PRECOMPILE_TRACE_COMPILE[] = <filename>`, Julia compilation will emit compilation traces with timing information.
=> Add timing when `PRECOMPILE_TRACE_COMPILE` is set (#57251)

src/gc.c, src/jl_uv.c
```Julia
function main()
t = Threads.@spawn begin
ccall(:uv_sleep, Cvoid, (Cuint,), 5000)
end
ccall(:uv_sleep, Cvoid, (Cuint,), 1000)
GC.gc()
wait(t)
end
main()
```
```
julia -t4 --timeout-for-safepoint-straggler=1 --safe-crash-log-file=/tmp/foobar.txt mwe.jl
```
Ran:
```
cat /tmp/foobar.txt 
```
And got:
```
{"level":"Error", "timestamp":"2025-02-04T18:27:20.513", "message": "===== Thread 2 failed to reach safepoint after 1 seconds, printing backtrace below =====\n"}
{"level":"Error", "timestamp":"2025-02-04T18:27:20.651", "message": "thread (1) __semwait_signal at /usr/lib/system/libsystem_kernel.dylib (unknown line)\n"}
{"level":"Error", "timestamp":"2025-02-04T18:27:21.651", "message": "===== Thread 2 failed to reach safepoint after 1 seconds, printing backtrace below =====\n"} …
```
=> Make sure backtrace printed by STW straggler goes into safe-log-file

src/threading.c
=> Use `uv_thread_equal` to compare thread IDs

base/loading.jl
Minor tweak to the error message: embed the exit code of the Julia child process that failed to compile the package.
=> Add exit code to `Base.compilecache` error message (#57455)

base/compiler/abstractinterpretation.jl, base/compiler/abstractlattice.jl, base/compiler/optimize.jl, base/compiler/ssair/inlining.jl, base/compiler/ssair/passes.jl, base/compiler/tfuncs.jl, base/compiler/typelattice.jl, base/compiler/typeutils.jl, test/compiler/inference.jl, test/compiler/inline.jl
Bring in two commits ([first](https://github.com/JuliaLang/julia/commit/1895479fd0c89e63abb772eb4b6b00519c74f1a8), [second](https://github.com/JuliaLang/julia/commit/4226f1e698b41e1d0537bc1845beb6eee1d612c0)) to fix [RAI-34444](https://relationalai.atlassian.net/browse/RAI-34444).
[RAI-34444]: https://relationalai.atlassian.net/browse/RAI-34444?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Backport inference fixes

src/gc.c, src/jloptions.c, test/threads_exec.jl
Let's enable the safepoint straggler bt printing unconditionally.
=> enable safepoint straggler bt printing unconditionally

src/julia-syntax.scm
Fix a failure introduced in https://github.com/RelationalAI/julia/pull/179.
The function that checks whether an AST node represents a `method` was incorrect in that PR.
This PR passes the relevant `show` tests in JuliaLang CI.
```Julia
julia-RAI % julia                                     
_
_       _ _(_)_     |  Documentation: https://docs.julialang.org
(_)     | (_) (_)    |
_ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
| | | | | | |/ _` |  |
| | |_| | | | (_| |  |  Version 1.10.2+RAI (2025-03-14)
_/ |\__'_|_|_|\__'_|  |  dcn-fix-name-canonicalization/614e7b85c2 (fork: 430 commits, 620 days)
|__/                   |
julia> Base.runtests(["show"])
Running parallel tests with:
nworkers() = 1
nthreads() = 1
Sys.CPU_THREADS = 4
Sys.total_memory() = 64.000 GiB …
```
=> [RAI-35987] Fix name canonicalization backport

src/signals-unix.c
Backports https://github.com/JuliaLang/julia/pull/57832 to fix the false alarms we've been getting in the GC crash monitor.
=> [Linux] Prevent GC from running during process teardown

src/pipeline.cpp
_What does this PR do?_
Port https://github.com/JuliaLang/julia/pull/57731.
=> [RAI-35958] Backport: Add passes to -O1 pipeline to reduce allocations in reinterpret

src/gf.c, src/julia_internal.h, stdlib/InteractiveUtils/docs/src/index.md, stdlib/InteractiveUtils/src/InteractiveUtils.jl, stdlib/InteractiveUtils/src/macros.jl, stdlib/InteractiveUtils/test/runtests.jl
Backports https://github.com/JuliaLang/julia/pull/55915
=> Backport: InteractiveUtils: add `@trace_compile` and `@trace_dispatch` (#55915)

src/gf.c, test/ambiguous.jl
_What does this PR do?_
backports https://github.com/JuliaLang/julia/pull/50962 (https://github.com/JuliaLang/julia/pull/57715/commits/3b03adef0d32da5874b913c0787e10afae366cdc)
to fix https://github.com/JuliaLang/julia/issues/57903
=> Backport: fix missing methods in ml_matches results (#50962)

src/array.c, src/gc-alloc-profiler.cpp
`rand()` locks and is slow. This uses the seed from `ptls`.
=> Use faster PRNG in the allocations profiler (#57761)

src/jloptions.c
Change the default from 60 seconds to 25 seconds.
=> Set safepoint straggler timeout to 25 secs

src/module.c, src/staticdata.c, src/staticdata_utils.c
This does not fix the underlying issue that can occur here which is a collision of build_ids.lo between modules in IR decompression. Fixing that requires a somewhat significant overhaul to the serialization of IR (probably using the module identity as a key). This does mean we use a lot more of the bits available here so it makes collisions a lot less likely( they were already extremely rare) but hrtime does tend to only use the lower bits of a 64 bit integer and this will hopefully add some more randomness and make this even less likely
=> Make build_id.lo more random (#58258)

src/staticdata.c
Manually backported: the stripping code has been refactored upstream. Discussion on [Slack](https://relationalai.slack.com/archives/C01BC96H69W/p1746720003439789).
These are used by `hasmethod`, and in any case including keyword argument symbols is unavoidable so there is no cost to keeping these.
=> don't strip keyword argument names with --strip-metadata (#58412)

src/datatype.c, test/core.jl
Manually backported -- `Base.datatype_isbitsegal` isn't present on 1.10.
This is caused because for LLVMs sake we have to say that the oddly typed field is smaller than it actually is. (I wonder if we could represent it as an iN field in a struct and have it work but the result would be the same for now)
=> Fix layout flags for types that have oddly sized primitive type fields (#58435)

src/gf.c
This is a quick-fix for an issue where methods that are inferred to return a `Const` do not emit compilation traces. Although they are never compiled by LLVM, we want to log them since they are inferred / compiled by Julia. As with https://github.com/RelationalAI/julia/pull/236, it isn't yet clear what the actual upstream fix will look like on 1.12+.
=> gf.c: include const-return methods in `--trace-compile`

base/loading.jl, test/precompile.jl
Pkg right now has to start a separate process to run precompilation for the test environment which is annoying for multiple reasons
Corresponding Pkg PR: https://github.com/JuliaLang/Pkg.jl/pull/3792
=> allow passing command line flags to `compilecache`. (#53316)

base/compiler/typeinfer.jl
Now that we re-export quite a lot from `Core` it seems sensible to remove. This allows constructors like `Tuple{Type{Vector{Foo}}, UndefInitializer, Tuple{Int}}` to precompile properly.
Appears to have a minimal effect on the stdlib pkgimages:
```julia
--- before.txt  2025-05-23 08:36:20.171870043 -0400
+++ after.txt   2025-05-22 14:48:49.003869097 -0400
@@ -47,7 +47,7 @@
20K ../julia/usr/share/julia/compiled/v1.13/Logging/pkgimage.so
20K ../julia/usr/share/julia/compiled/v1.13/Logging/pkgimage.so
3.5M ../julia/usr/share/julia/compiled/v1.13/Markdown/pkgimage.so
-3.6M ../julia/usr/share/julia/compiled/v1.13/Markdown/pkgimage.so
+3.5M ../julia/usr/share/julia/compiled/v1.13/Markdown/pkgimage.so
184K ../julia/usr/share/julia/compiled/v1.13/Mmap/pkgimage.so
184K …
```
=> Don't filter `Core` methods from newly-inferred list

base/loading.jl, src/gf.c, src/jl_exported_funcs.inc
Backport PR JuliaLang/Julia#58805
Alternative to https://github.com/JuliaLang/julia/pull/58146.
We want to compile a subset of the possible specializations of a function. To this end, we have a number of manually written `precompile` statements. Creating this list is, unfortunately, error-prone, and the list is also liable to going stale. Thus we'd like to validate each `precompile` statement in the list.
The simple answer is, of course, to actually run the `precompile`s, and we naturally do so, but this takes time.
We would like a relatively quick way to check the validity of a `precompile` statement.
This is a dev-loop optimization, to allow us to check "is-precompilable" in unit tests.
We can't use `hasmethod` as it has both false positives (too loose):
```julia
julia> hasmethod(sum, …
```
=> Backport PR #58805

src/gf.c
Backport https://github.com/JuliaLang/julia/pull/59012. Improve --trace-dispatch coverage.
=> Improve --trace-dispatch coverage: emit it in "full-cache" fast path as well. (#59012)

src/gf.c, test/core.jl
Backports https://github.com/JuliaLang/julia/pull/59327.
Original PR description:
> Fixes https://github.com/JuliaLang/julia/issues/59326.
> 
> Change the logic that decides not to specialize a function parameter based on whether or not the supplied argument is a Function, and that function is not used, so that it will still work if the SpecType is a Union{Function,Nothing} or any other union that contains a Function.
> 
> The logic is changed from a hardcoded rule of `type_i == Function || type_i == Any || type_i == Base.Callable` to `type_i >: Function`.
> 
> This covers all of the above cases, but also includes custom `Union{Function, T}` such as `Union{Function, Nothing}`.
> 
=> Fix nospecializing Functions in `Union{Nothing,Function}` params (#59327)
